version: '3'

services:
  front-end:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - proxy

  proxy:
    image: nginx:latest
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end-1
      - back-end-2

  back-end-1:
    image: flask-api
    build:
      context: ./api
    ports:
      - "5000"

  back-end-2:
    image: flask-api
    build:
      context: ./api
    ports:
      - "5000"
